apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: test-macvlan-network
  namespace: test-macvlan-namespace
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "test-macvlan-network",
      "type": "macvlan",
      "master": "eno1.129",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }
