---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - allocating-resources
  - garbage-collection
  - sctp

resources:
  - small-pods-worker-label.yml
  - small-pods-master-label.yml
