apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name:
    99-worker-kargs
spec:
  kernelArguments:
    - rd.driver.pre=ahci
    - rd.driver.post=mpt3sas
