kind: Secret
apiVersion: v1
metadata:
  name: rook-ceph-external-cluster-details
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "4"
stringData:
  external_cluster_details: |
    [ EXTERNAL_CLUSTER_SECRETS ]
