---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-performance-addon-operator-subscription
  namespace: openshift-performance-addon-operator
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  channel: "4.8"
  name: performance-addon-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
