bmc_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
bmc_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
pullSecret: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
argocd_git_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
argocd_git_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
cluster_ssh_public_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
kubeconfig_certificate_authority_data: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
kubeconfig_client_certificate_data: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
kubeconfig_client_key_data: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
kubeconfig_context_user: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
kubeconfig_context_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          ENCRYPTED_DATA
